version: "3.8"

services:

  mysql:
    container_name: mysql
    image: mysql:8.0.29
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: authorbookdb
      MYSQL_USER: authorbookuser
      MYSQL_PASSWORD: authorbookpass
      MYSQL_ROOT_PASSWORD: secret
    healthcheck:
      test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"

  mongodb:
    image: bitnami/mongodb:5.0.9
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGODB_DATABASE: bookreviewdb
      MONGODB_USERNAME: bookreviewuser
      MONGODB_PASSWORD: bookreviewpass
      MONGODB_ROOT_PASSWORD: secret
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/bookreviewdb --quiet

  zipkin:
    image: openzipkin/zipkin:2.23.18
    container_name: zipkin
    restart: unless-stopped
    ports:
      - "9411:9411"
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "9411" ]
